name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches-ignore: [ ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    name: Build and Run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile with make
        run: make

      - name: Start server
        run: ./servidor

      - name: Run client
        run: ./cliente 4
