name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches-ignore: []

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    name: Build and Run

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile with make
        run: make

      - name: Start server
        run: |
          make
          ./servidor &

      - name: Run client
        run: |
          sleep 5 # Esperar 5 segundos para asegurar que el servidor se inicie correctamente
          ./cliente 4 0.0.0.0
          pkill -f ./servidor # Finalizar el proceso del servidor
